name: Extract and code with Bash and python
on: push
jobs:
  extract-data:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Print hello world
        run: echo hello world
