name: Extract and code with Bash and python
on: [push]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract current PR Number
        run: |
          echo PR_NUMBER=$(gh pr view --json number -q .number) >> $GITHUB_ENV
      - name: print pr number
        run: echo $PR_NUMBER  
      - name: Fetch file name that was changed
        id: fetch-filename
        run: |
          echo "CHANGED_FILENAME=$(gh pr view 2 --json files --jq '.files.[].path'| grep -i '.md')">>$GITHUB_ENV
      - name: print
        run: echo $CHANGED_FILENAME



